### ISSUE TITLE
Icon selection not saving

### ISSUE THREAD

**Issue by michaelroper** [verbb/icon-picker#1]
### Description

Hey Josh! Not sure when this started happening, but it _was_ working fine when I first grabbed the plugin... but on the latest commit, when I select an icon and save the entry, the selection is empty when the entry page is reloaded! 😱

Works if I rollback to 98a4e09 😄 

### Steps to reproduce

1. Select Icon, save entry
2. When entry is reloaded, icon picker field is empty

### Additional info

- Plugin version: 3b6ecba

**Comment by engram-design** [comment]
Fixed in [1.0.0.1](https://github.com/verbb/icon-picker/releases/tag/1.0.0.1)

**Comment by fa6ian** [comment]
Hi Josh,

I have the latest version installed (1.0.8), and I'm still encountering this issue.

Any thoughts?

**Comment by engram-design** [comment]
@fa6ian What sort of icons are you trying to add - fonts, single SVG, SVG sprites, Font Awesome?

Is the site a multi-site? Is the field a solo field, or in a Matrix/SuperTable/etc field?

**Comment by engram-design** [comment]
Closing due to age. Let me know if this is still occurring
