### ISSUE TITLE
Font Awesome 6 icons search issues

### ISSUE THREAD

**Issue by sanderpotjer** [verbb/icon-picker#76]
### Describe the bug

When searching for icons the incorrect icons are visible. E.g.:
<img width="1020" alt="Schermafbeelding 2023-02-24 om 15 57 46" src="https://user-images.githubusercontent.com/522834/221213061-320528bd-80c9-413c-8830-942199148a85.png">
<img width="1017" alt="Schermafbeelding 2023-02-24 om 15 57 52" src="https://user-images.githubusercontent.com/522834/221213074-3592d7a5-f6cf-4050-800d-761b23b5fe18.png">
<img width="1023" alt="Schermafbeelding 2023-02-24 om 15 57 57" src="https://user-images.githubusercontent.com/522834/221213080-6c41b1f9-34b5-48d7-8031-7be68d9ffd8e.png">
<img width="1023" alt="Schermafbeelding 2023-02-24 om 15 58 05" src="https://user-images.githubusercontent.com/522834/221213086-b79f843c-8db0-4fa8-8ae3-0ac32acf1bd2.png">
<img width="1017" alt="Schermafbeelding 2023-02-24 om 15 58 11" src="https://user-images.githubusercontent.com/522834/221213091-91c8c0ec-7613-4816-991a-492ecabdce74.png">
<img width="1022" alt="Schermafbeelding 2023-02-24 om 15 58 18" src="https://user-images.githubusercontent.com/522834/221213096-e7ef6b32-a6b0-41a7-a407-36afc798b7cf.png">

As you can see when searching for `c`, `ch`, `cha` the same icons remain visible while the labels below the icons change. 

### Steps to reproduce

1. Use Font Awesome 6 via a Kit
2. Search for `chart bar` as example

### Craft CMS version

4.3.10

### Plugin version

2.0.12

### Multi-site?

Yes

**Comment by engram-design** [comment]
This would be down to the virtual scroll list we use to aid in performance, but I can't seem to replicate that. There was a similar issue that was fixed in 2.0.12.

Are you able to go on the `craft-4` branch just to test? To do this, run `composer require verbb/icon-picker:"dev-craft-4 as 2.0.12"`.

Just to show my output of `c`, `ch`, `cha`, `char`, `chart`.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1221575/221340874-d9437cb9-7431-4c78-8d07-95a249da550c.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/1221575/221340879-ac96ff2d-11f3-4010-aabc-da924c771409.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/1221575/221340885-e8b02a5a-72b2-47e3-9030-4a8925fde935.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1221575/221340892-cb3a17c1-86c8-4b66-a785-8ee7af284aa2.png">

<img width="765" alt="image" src="https://user-images.githubusercontent.com/1221575/221340902-cd4811e3-48b7-4d96-b313-137c81d3400d.png">

**Comment by sanderpotjer** [comment]
@engram-design thanks, unfortunately this doesn't solve the issue. Can I provide you any specific info?

**Comment by engram-design** [comment]
Hmm. I can see this is also inside a Super Table field. Do you see the same behaviour when outside of that? I also assume you've cleared the Icon Picker caches as well.

Wondering, if possible, if you can send through your kit details to `support@verbb.io` just in case there's something specific about that?

Otherwise, I'm not _quite_ sure how to replicate what you're seeing...

**Comment by sanderpotjer** [comment]
@engram-design initially the field was used in a Matrix field, yesterday I tried as a single Icon Picker field as well and no other icon instances are on that test-section, same behavior. The weird thing is that if I type until `chartt` (so it has no results) and remove one character, the correct icons are displayed. See video clip below:

https://user-images.githubusercontent.com/522834/221789904-daff8beb-589f-46ef-be33-0f69460d9258.mov

Will send the kit details by mail.

**Comment by engram-design** [comment]
Thanks for sending that info through - that's exactly what's got it replicated for me! I believe this may be down to your Kit Settings in Font Awesome.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1221575/221843232-31ad11fa-4798-4baa-aa35-4ff2a0d9e9ac.png">

You'll need to ensure this is set to "Web Fonts" and not "SVG". This is because using SVGs, the Font Awesome JS will insert the SVG dynamically into each slot in the icon picker pane. But because we utilize a virtual scroller component that drastically improves the UI performance, that won't work. That's because each square is a reused DOM component, and that won't work when they change via filtering. As we're seeing - the contents of the DOM (the SVG) don't match up with the label.

Let me know if that doesn't work!

**Comment by sanderpotjer** [comment]
@engram-design requested our client to add another kit with the "Web Fonts" as setting and that indeed solved the issue! So thanks a lot for your support! :) 

Maybe add this info to the documentation on https://verbb.io/craft-plugins/icon-picker/docs/feature-tour/icon-sets#kits or help text in settings?

**Comment by engram-design** [comment]
Agreed, totally forgot myself that it was a "requirement". Updated now.
